import React from 'react'
import './tyranids.css'
import NavBar from '../NavBar/NavBar.jsx'
import Footer from '../Footer/Footer.jsx'
import tyranidsLogo from '../../assets/tyranidsLogo.png'
import HiveTyrants from '../../assets/Hive Tyrants.jpg'
import Broodlords from '../../assets/Broodlords.jpg'
import TyrantGuards from '../../assets/Tyrant Guard .jpg'
import TyranidWarriors from '../../assets/Tyranid Warriors.jpg'
import Lictors from '../../assets/Lictors.jpg'
import Gaunts from '../../assets/Gaunts.jpg'
import Gargoyles from '../../assets/Gargoyles.jpg'
import Rippers from '../../assets/Rippers.jpg'
import Genestealers from '../../assets/Genestealers.jpg'
import Carnifexes from '../../assets/Carnifexes.jpg'
import Raveners from '../../assets/Raveners.jpg'
import Zoanthropes from '../../assets/Zoanthropes.jpg'
import Biovores from '../../assets/Biovores.jpg'
import BioTitans from '../../assets/Bio-Titans.jpg'
import NornQueens from '../../assets/Norn-Queens.jpg'
import Dominatrixs from '../../assets/Dominatrixs.jpg'
import Trygons from '../../assets/Trygons.jpg'
import Mawlocs from '../../assets/Mawlocs.jpg'
import HiveGuard from '../../assets/Hive Guard.jpg'




function Tyranids() {
    return (
        <>

            <NavBar />
            <div id='containerTyranids'>
                <main className='mainTyranidSection'>
                    <section className='tyranidsMainInfo'>
                        <h4><img src={tyranidsLogo} alt="" className='tyranidsLogo' />Tyranids info <img src={tyranidsLogo} alt="" className='tyranidsLogo' /></h4>
                        <p>The Tyranids are an extragalactic composite species of hideous, insectoid xenos. They actually comprise an entire space-faring ecosystem comprised of innumerable different bioforms which are all variations on the same genetic theme.</p>
                        The Tyranids are unlike any other intelligent species encountered by Humanity. They are the ultimate predators; to them, all living things, from the lowliest insect to the most advanced starfaring civilisation, are mere prey. Only now are the inhabitants of the galaxy realising the scale of the threat; unless the Tyranids can be stopped, it will mean nothing less than the extinction of all life.
                        <p>The Tyranid species is ultimately dedicated solely to its own survival, propagation and evolutionary advancement. The Tyranids collectively form a monstrous superorganism that travels across the universe in their great hive fleets of biomechanical Hive Ships, systematically consuming all other biomatter to enable their own rapid evolution and reproduction.</p>
                        <p>The Tyranids are likened to a galactic swarm consuming everything in its path, feeding on entire worlds and leaving only dead husks in their wake. Their threat is such that an unprotected planet can be infested and stripped clean of all its organic material in a matter of solar weeks without even slowing down the advance of the hive fleet.</p>
                        <p>All Tyranid organisms are "synaptic" (psychically-reactive), and each Tyranid creature within a hive fleet shares and contributes to a communal Hive Mind, which allows the trillions of beings comprising the Tyranid hive fleets to communicate and organise instantaneously on a staggering scale.</p>
                        <p>The mentality of the Tyranid approach to warfare can be described with the phrase "quantity has a quality all its own." From the "lowly" Ripper, to the deadly Hive Tyrant and beyond, the signature of the Tyranid species is that they overwhelm their foes with sheer numbers, reproducing massive numbers of highly virulent organisms in record time from the biochemical soup that they derive from the biospheres of the worlds they consume.</p>
                        <p>The components of a Tyranid hive fleet travel almost exclusively in large groups known as "swarms" that possess specialised biomechanical creatures for destroying and consuming a wide variety of prey life forms.</p>
                        <p>The Tyranids have evolved sophisticated methods for facilitating genetic transfer across species boundaries. As a result, a significant goal of any Tyranid invasion is acquisition of useful new biological traits from other lifeforms.</p>
                        pThese are used by the Hive Mind to enhance the Tyranids' effectiveness in consuming new worlds to gain more of the necessary organic raw materials for further reproduction and directed evolution. All Tyranids are reproduced by a single, highly intelligent female bioform known as a Norn-Queen.
                        pA hive fleet's Norn-Queens are the most important Tyranids within the fleet, for if they are injured or killed the Tyranids cannot reproduce their numbers from the captured bio-mass. As a result, Norn-Queens can be found only at the heart of the largest and most-well defended Tyranid Hive Ships.
                    </section>
                    <section className='tyranidHistoySection'>
                        <h4>History</h4>
                        <h5>Tyrannic Wars</h5>
                        <p>The Tyranids are not native to the galaxy; they have journeyed across the unspeakable cold of the void, where time and space conspire to hold the stars apart with inconceivable distances.</p>
                        <p>Yet the Tyranids crossed this expanse nonetheless, moving through the empty darkness for countless millennia to reach the rim of the galaxy.
                        </p>
                        <p>Who can say for sure what could compel an entire species to make such a venture? Perhaps the Tyranids have already consumed everything of worth in their home galaxy and must find new feeding grounds or starve.
                        </p>
                        <p>It is possible that the Tyranids have been preying on galaxies since time immemorial and this is but the latest to feel their predations.</p>
                        <p>Some have even speculated that the Tyranids are in flight from an even greater threat, be it a cosmic disaster or another fearsome alien threat, and have risked the nothingness between galaxies rather than face extinction.</p>
                        <p>Whatever the truth, for the Tyranids to have endured such a voyage must have required utter single-mindedness and unimaginable energy. During their journey, the Tyranids slumbered in a state of frozen hibernation, but now they have arrived, they have awoken and they are hungry.</p>
                        <p>The first recorded contact between the Imperium and the Tyranids places their appearance in the Eastern Fringes of the galaxy in 745.M41. However, it is rumoured that the Ordo Xenos of the Inquisition had identified possible appearances of this xenos species as far back as the 35th Millennium.</p>
                        <p>The xenos emerged from the intergalactic space of the Local Group of galaxies, their Hive Mind drawn to the Milky Way by the psychic beacon of the Astronomican transmitted by the Emperor's presence in the Warp from Terra.</p>
                        <p>The first officially recorded contact with the Tyranids for the Imperium of Man came during a Tyranid attack on an Ocean World called Tyran, and from there Hive Fleet Behemoth continued directly towards the centre of the galaxy, consuming all the worlds in its path.</p>
                        <p>The Tyranids were defeated, barely, by the efforts of the Ultramarines Chapter of the Space Marines during the Battle of Macragge, although the Ultramarines suffered devastating losses that would take centuries to replace.</p>
                        <p>In 942.M41, Commissar Ciaphas Cain, while on a mission on the Ice World of Nusquam Fundumentibus, discovered hibernating Tyranids buried deep in the permafrost; the swarm was apparently carried to the planet by a Hive Ship that had crashed on the planet seven millennia earlier, prior to any human colonisation.</p>
                        <p>Members of the swarm and subsequently, the Hive Mind, were awakened, but this swarm was eventually defeated. However, the Inquisition was unsettled by the fact that the Tyranids had developed a presence in the galaxy possibly before even the start of the Age of the Imperium.</p>
                        <p>It is not known whether the crashed bio-ship was on a scouting mission when it was lost, was a casualty in a pre-Imperial Tyranid invasion force that was defeated by unknown adversaries, or part of a plan by a Tyranid super-intelligence that may have "seeded" the galaxy with many such slumbering broods.</p>
                        <p>In 993.M41 the Tyranids returned to the galaxy with Hive Fleet Kraken which, instead of assaulting its targets as a single massed Hive Fleet, split into countless smaller fleets, each enveloping whole star systems before reinforcements could arrive.</p>
                        <p>The brunt of this new attack was borne by the Space Marine Chapters known as the Scythes of the Emperor and the Lamenters; the former Chapter was almost completely destroyed.</p>
                        <p>Though the backbone of the hive fleet was broken by its defeats at the Battle of Ichar IV and at the Aeldari Craftworld Iyanden, the cost to the Imperium was still great and many splinter fleets broke off from the Kraken to later wreak havoc deep within Imperial space, even reaching as far as the fringes of the T'au Empire.</p>
                        <p>Just as it seemed the defences of the Segmentum Solar and perhaps Terra itself would be tested, the Tyranids were distracted by being deflected into the star system of the powerful Ork Empire of Octarius in the Octarius Sector of the Segmentum Ultima.</p>
                        <p>While the Orks managed to stall the main Tyranid hive fleet's advance in what has become known as the Octarian War, tendrils of the Leviathan have already begun to reemerge from these battles, victorious and stronger than ever after having absorbed potent Orkoid genetic material into their own genetic pool.</p>
                    </section>
                    <section className='tyranidCombatDoctrieSectionn'>
                        <h4>Tyranid Combat Doctrine</h4>
                        <p>Tyranids often attempt to first conquer a planet through subterfuge and infiltration. Space Hulks and other derelict spacecraft are infested with Genestealers, which quickly familiarise themselves with the layout of their new home, then enter hibernation.</p>
                        <p>When the hulk is eventually discovered by Imperial authorities, the Genestealers attack the exploration crew, sometimes killing some crew members, but always leaving at least one survivor who is implanted with a seed, a form of Genestealer reproductive virus that contains specially-engineered Tyranid DNA.</p>
                        <p>This infestation is never fatal, but instead the virus' genetic material subtly alters the victim's DNA, producing in them a strong urge to mate created by the stimulation of the individual's sex hormones.</p>
                        <p>The Genestealer DNA will be incorporated into the host's germ cells and so any child that results from this union will be a Genestealer hybrid, which now has the complete loyalty of its parents through a psychic bond.</p>
                        <p>The hybrids continue to breed and multiply among the population of the host species, eventually forming a Genestealer Cult. As the cult grows in numbers, it begins to spread its influence throughout the planet's political and social structure, placing its members in positions of power within the government and the military.</p>
                        <p>At the same time, the cult's hybrid members, united by a smaller psychic gestalt known as the Broodmind, begin to emit a collective psychic signal through the Warp that acts as a beacon for the approaching Tyranid hive fleet.</p>
                        <p>As the Tyranid Hive Fleet nears the doomed world, the Genestealer Cult, potentially numbering in the millions by this point, goes into action, instigating a worldwide rebellion with the goal of weakening the planet's defences against the approaching hive fleet.</p>
                        <p>The hive fleet will also seed the planet with numerous Tyranid organisms, which will begin to biologically alter the planet's climate, surface and ecosystems to make it easier to consume.</p>
                        <p>If the hive fleet is victorious, the fleet will descend to the planet, inhaling the atmosphere, drinking the seas, and basically consuming all organic biomass until nothing more than a lifeless ball of rock remains.</p>
                        <p>On the battlefield, Tyranid tactics are based around the notion of superior numbers, as they generally try to outnumber the enemy fifty to one. Tyranids overrun opposition in close combat, closing faster than most armies.</p>
                        <p>They possess few ranged weapons, but their sheer numbers and close combat specialisation makes up for the slaughter if they are led by a capable commander.</p>
                        <p>The Tyranids do not communicate with other intelligent species, and why should they do so? Tyranids are as far above other life forms, such as humanity, just as humanity is above the domesticated livestock it consumes.

                        </p>
                        <p>The Tyranids cannot be reasoned with, appeased or surrendered to. There can be no hope of mercy from such a foe. To face the Tyranids is simply a matter of survival: kill or be consumed.</p>
                        <p>Vast swathes of the galaxy have already been stripped of life, and with every passing Terran year the hive fleets push deeper into regions of populated space. Even as the prey races direct their forces to repel these threats, still more Tyranid fleets approach from the intergalactic void and emerge from their aeons-long slumbers.</p>
                        <p>The thought processes of the Hive Mind are gathering pace as more Tyranids wake and recall the age-old purpose of their kind -- feed, grow, survive, and evolve.</p>
                    </section>
                    <section className='tyranidSpeciesSection'>
                        <h3>Tyraniid Species</h3>
                        <p>Tyranids appear in a multitude of genera, and all have an extremely rapid rate of evolution directed by the Hive Mind, adapting to threats in direct response to their presence. Tyranid matter is constantly reabsorbed into biomass reclamation pools to create new species and adapt existing ones to suit the Hive Mind's immediate purpose.</p>
                        <ul className='tyranidsList'>
                            <li className='tyranidsObjectList'><p>
                                Hive Tyrants - The Hive Tyrants are large and enormously strong Tyranids, who act as the leaders of the swarm and a synaptic conduit for the smaller creatures. They are highly psychic and highly mutable, and have a closer connection to the Hive Mind than most other genera of Tyranids. They are skilled at both close combat and ranged attack, more so than most other Tyranid organisms. Sometimes they are spawned with wings. Imperial Techno-Magi believe that Hive Tyrants are the repository of a Hive Fleet's collective consciousness, which means they completely embody the Hive Mind, yet their destruction does not in any way diminish its presence.
                            </p><div><img src={HiveTyrants} alt="" className='tyranidsTypeImgSize' /></div>
                            </li>
                            <li className='tyranidsObjectList'><p>Broodlords - The Broodlords are another Tyranid synaptic organism, regarded as the epitome of the Genestealer breed. The Broodlord is one of the first Genestealers to make planetfall on a victim world. They are devastating in combat and are specifically adept at infiltration on the battlefield to get closer to the enemy. They are very adaptable and highly intelligent. Broodlords are also the center of Genestealer Cults, and they coordinate the cult's attacks. If the Broodlord is killed, then one of the purestrain Genestealers will eventually evolve into a new Broodlord after a period of time.</p><div><img src={Broodlords} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Tyrant Guard - The Tyrant Guards are a special species of Tyranid spawned in small broods for the sole purpose of defending the Hive Tyrant. They are large, tough, and difficult to harm, and it is nearly impossible to surpass their defense. Tyrant Guard are completely blind, utterly controlled by the synapse creatures they protect. On occasion Carnifex also benefit from the Tyrant Guard's protection. Tyrant Guard are believed by some Adeptus Mechanicus Magi to contain the DNA of the defeated Space Marine Chapters, but the Imperium considers this blasphemy and denies its very likely possibility.</p><div><img src={TyrantGuards} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Tyranid Warriors - The Tyranid Warriors are synaptic foot troops for the swarm. In between the size of a Hive Tyrant and a Gaunt, they serve as psychic resonators and assist in guiding the lesser Tyranid troops into battle. They are fast and powerful, with the capability to be strong at ranged combat or in close quarters in a similar fashion to the Hive Tyrant. </p><div><img src={TyranidWarriors} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Lictors - The Lictors are large, deadly organisms bred for their stealthy qualities. A Lictor is basically chameleonic in nature, allowing it to blend with its surroundings to hunt and later kill its prey. Lictors are usually only seen when the Tyranids are springing a deadly ambush onto an unsuspecting army, unleashing a bio-engineered killing machine within their own ranks. They range ahead of the swarms, performing commando raids of sorts, and gathering information by devouring their victim's brains. The Lictors possess stealth and cunning of an unprecedented scale - to a point where they can best the famous Catachan fighters in jungle combat. Many Imperial Guard commanders have lost their troops in the shadows as they blink for a second; that is the terrifying undetectable Lictor at work.</p> <div><img src={Lictors} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Gaunts - The Gaunts are the basic staple combat unit of a Tyranid swarm. They are smaller and less physically powerful than most other Tyranid organisms, but they are extraordinarily adaptable and always attack in large numbers. They are a fully mutable species, and some are grown with extra wings, adrenaline/venom sacs, and even bizarre biomechanical weaponized symbiotes, including the dreaded spike rifle.</p><div><img src={Gaunts} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p> Gargoyles - The Gargoyles are essentially winged variants of the Gaunt genus. They possess many similar traits, including a smaller size and physical prowess than most Tyranid organisms. Gargoyles retain most of the physical traits of Gaunts, however, and their lower legs have atrophied to little more than stumps. Like their cousin, the Gaunt, they are capable of being armed with a large host of biomechanical, symbiotic weaponry. </p><div><img src={Gargoyles} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Rippers - The Rippers are small, snake-like organisms designed to devour biomatter so that new DNA and nutrients can be absorbed by the Hive ships. They are released in the final stage of a Tyranid invasion.</p><div><img src={Rippers} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Genestealers - The Genestealers are ferocious humanoid creatures, supposedly derived from human DNA, that are used as a vanguard to the Tyranid invasions of the Imperium. They infiltrate human societies, creating Genestealer Cults, as described under the tactics section above. They are also used as shock troops on the battlefield, where their sharp claws and instinctive close combat skills allow them to tear heavily armed opponents to shreds.</p><div><img src={Genestealers} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Carnifexes - The Carnifexes are originally known as screamer-killers are huge, hulking, living battering rams, armed with a variety of biomechanical, symbiotic weaponry. Even stronger than the Hive Tyrants, they are used for assaulting fortified positions and as armor formations, such as during boarding actions. Carnifexes are the Tyranid equivalent of tanks or Space Marine Dreadnoughts - and the monstrous creatures can be mutated into a multitude of different sub-species, some designed for tank hunting, others built to produce acid and toxins ideal for anti-infantry combat.</p><div><img src={Carnifexes} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Raveners - The Raveners appear to be related to both Rippers and Tyranid Warriors. These large beasts are designed for fast assaults against lighter enemies, and dig through the ground to perform surprise raids.</p><div><img src={Raveners} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Zoanthropes - The Zoanthropes are a type of psychic artillery, whose highly evolved brains swell out of proportion with their bodies. Through their use of psychic powers they can perform a number of roles on the battlefield. Some evidence points to later incarnations of Zoanthropes being improved by the Hive Mind's assimilation of Aeldari DNA following the Hive Fleet Kraken Tyranid assault on the Craftworld Iyanden.</p><div><img src={Zoanthropes} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Biovores - The Biovores are sluggish, sessile creatures, whose only task is to grow and launch Spore Mines towards the enemy. The Spore Mines grow inside the Biovore's body, and are then hurled across the battlefield through a muscle spasm. Biovores are supposedly evolved from Orkish gene-stock. </p><div><img src={Biovores} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Bio-Titans - The Bio-Titans are enormous organisms, evolved as a response to other races' Titans and other super-heavy warmachines. They are (as of yet) the largest land-based Tyranid creatures encountered. They range from nine to thirty metres tall, and can single-handedly take out an entire squad of Space Marines. </p><div><img src={BioTitans} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Norn-Queens - The Norn-Queens are gargantuan organisms that are essentially biomechanical wombs that give birth to all of the other known Tyranid life forms. They can biochemically and genetically manipulate biomass in infinite ways to create new organisms to serve any function the Tyranid race requires. The Norn Queens are housed in huge rooms aboard the Hive Ships. Each room is hundreds of metres high, filled with a single Norn Queen.</p><div><img src={NornQueens} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Dominatrixs - The Dominatrixs are the Norn-Queen's link to the Tyranid ground forces. They are huge monsters, almost as large as a Bio-Titan and the stronger, more psychically-powerful female Hive Tyrant. They are symbiotically fused with a smaller (Warrior-sized) entity which acts as a psychic, synaptic link to the linked Norn-Queen aboard her ship. </p><div><img src={Dominatrixs} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Trygons - The Trygons are powerful serpentine organisms that tunnel behind enemy lines. Towering over even a Carnifex, Trygons are one of the most powerful Tyranids breeds in existence. Trygons can also become synapse creatures to control other Tyranids. Trygons can lead a force of Tyranids known as a 'Tunnel Swarm'. This swarm is usually comprised of Lictors and Hormagaunts. The armour of a Trygon vibrates as it moves, thus creating a bio-electric current which can be released at will on a group of foes.</p><img src={Trygons} alt="" className='tyranidsTypeImgSize' /></li>
                            <li className='tyranidsObjectList'><p>Mawlocs - The Mawlocs are a subspecies of the Trygon. They are worm-like and blind, though they are incredibly agile despite their size. Their short claws are not suited for close combat, rather to tunnel efficiently under the battlefield, although they are by no means defenseless. They prefer to swallow their prey whole to be digested alive for several days. Despite being blind, the Mawloc can gather information of the surface through pressure waves since they can travel through solid and fluid objects below ground. When a Mawloc begins to home in on the enemy, severe tremors errupt on the surface, which can tell the Mawloc where its prey is with more accuracy. If the sound is regular and rhythmic, it is easier for the Mawloc to home in on. Even a heartbeat will tell it where its next meal is.</p><div><img src={Mawlocs} alt="" className='tyranidsTypeImgSize' /></div></li>
                            <li className='tyranidsObjectList'><p>Hive Guard - The Hive Guard are charged with protecting Tyranid structures and are capable of unleashing salvo after salvo of intense firepower. Essentially gun-beasts, they are heavily armoured in a shell-like carapace and have a body designed to be a stable firing platform for the massive impaler cannon bonded to their forelimbs. Physically linked to the shard-beasts that comprise the ammunition of their cannons, Hive Guard can target enemies with unerring accuracy - even those who they cannot see because they can receive sensory impressions from the shard bests in mid-flight.</p><div><img src={HiveGuard} alt="" className='tyranidsTypeImgSize' /></div></li>
                        </ul>
                    </section>
                </main>

            </div>
            <footer>
                <Footer />
            </footer>
        </>
    )
}

export default Tyranids