import React from 'react'
import './Necrons.css'
import NavBar from '../NavBar/NavBar'
import Footer from '../Footer/Footer'

function Necrons() {
    return (
        <>
            <NavBar />
            <div id='containerNecrons'>
                <main className='necronsMainInfo'>
                    <section className='necronsMainInfoSection'>
                        <h2>Necrons</h2>
                        <p>The Necrons are a mysterious xenos species of humanoid, robotic skeletal warriors that have lain dormant in their stasis-tombs for more than 60 million Terran years, though they have begun to awaken at last. They are the soulless creations and former servants of the ancient C'tan, the terrible Star Gods of Aeldari myth.</p>
                        <p>The Necrons are ancient beyond reckoning, predating even the birth of the Aeldari. At long last, however, they are beginning to awaken from their Tomb Worlds, for the galaxy is ripe for conquest and the restoration of the Necron Empire since the disappearance of the Old Ones more than 60 million standard years ago.</p>
                        <p>The Necrons are a completely robotic humanoid species whose technological prowess is probably unmatched by any of the other intelligent species of the galaxy.</p>
                        <p>Yet out of a desire for vengeance against the more fortunate long-lived, ancient xenos people called the Old Ones, and the trickery of the godlike intelligences known as the C'tan, the Necrons shed their original organic forms and lost all forms of compassion and empathy.</p>
                        <p>They have become instead ruthless, undying killing machines who are determined to exert their mastery over the galaxy once more</p>
                        <p>Across the galaxy, this ancient and terrible species is stirring back to life. Entombed in stasis-crypts for millions of Terran years, they have slumbered through the aeons, waiting for the galaxy to heal from the wounds of a long and bloody war.</p>
                        <p>Now, after sixty million standard years of dormancy, a great purpose begins. On desolate worlds thought long-bereft of all life, ancient machineries wake into grim purpose, commencing the slow process of revivification that will see those entombed within freed to stride across the stars once again. The unstoppable, undying Necron legions are rising. Let the galaxy beware.</p>
                        <p>All Necrons, from the lowliest of warriors to the most regal of lords, are driven by one ultimate goal, to restore their ancient ruling dynasties to glory and to bring the galaxy under their rule once more, as it was in ancient days.</p>
                        <p>Such was the edict long ago encoded into the Necrons' minds, and it is a command so fundamental to their being that it cannot be denied. Yet it is no small task, for the Necrons are awakening from their Tomb Worlds to find the galaxy of the 41st Millennium as recorded by the Imperial Calendar much changed.</p>
                        <p>Many Tomb Worlds are no more, destroyed by cosmic disaster or alien invasion. Others are damaged, their entombed legions afflicted by slow madness or worn to dust by entropy's irresistible onset.</p>
                        <p>Degenerate alien species squat amongst the ruins of those Necron Tomb Worlds that remain, little aware of the greatness they defile with their upstart presence. Yet there is no salvation to be found in such ignorance. The undying have come to reclaim their lands, and the living shall be swept aside.</p>
                        <p>Yet if billions of Necrons have been destroyed by the passage of eternity, countless billions more remain to see their dominion reborn. They are not creatures of flesh and blood, these Necrons, but android warriors whose immortal forms are forged from living metal. As such, they are almost impervious to destruction, and their mechanical bodies are swift to heal even the gravest wounds.</p>
                        <p>Given time, severed limbs reattach, armour plating reknits and shattered mechanical organs are rebuilt. The only way, then, to assure a Necron's destruction is to overwhelm its ability to self-repair, to inflict such massive damage that its ancient regenerative systems cannot keep pace.</p>
                        <p>Even then, should irreparable damage occur, the Necron will often simply "phase out" -- an automated viridian teleportation beam returning it to the safety of the stasis-crypts, where it remains in storage until such time as repairs can be carried out.</p>
                        <p>The sciences by which such feats are achieved remain a mystery to outsiders, for the Necrons do not share their secrets with lesser species and have set contingencies to prevent their supreme technologies from falling into the wrong hands. Should a fallen Necron warrior fail to phase out, it self-destructs and is consumed in a blaze of emerald light.</p>
                        <p>Outwardly, this appears little different to the glow of teleportation, leaving the foe to wonder whether the Necron has finally been destroyed or has merely retreated to its tomb. Victory over the Necrons is therefore always a tenuous thing, and a hard-won battle grants little surety of ultimate victory.</p>
                        <p>For the Necrons, defeats are minor inconveniences -- the preludes to future triumphs, nothing more. Immortality has brought patience; the perils that the Necrons survived in ancient times carry the lesson their people can overcome any opposition, if they have but the will to try. And if the Necrons possess only a single trait, it is a will as unbending as adamantium.</p>
                        <p>Only one hope can now preserve the other intelligent species of the galaxy from the Necrons' advance, from the endless legions of silent and deathless warriors rising from long-forgotten tombs. If the Necrons can be prevented from waking to their full glory, if the scattered Tomb Worlds can be prevented from unifying, then there is a chance of survival.</p>
                        <p>If not, then the great powers of the galaxy will surely fall, and the Necrons shall rule supreme for all eternity -- undying, cruel and utterly implacable.</p>
                        <p></p>
                        <p></p>

                    </section>
                    <section className='warInHavenSection'>
                        <h2>War in Haven</h2>
                        <p>The terrible wars between the Old Ones and the Necrontyr that followed, known later in Aeldari myth as the War in Heaven, would fill a library in their own right, but the Necrontyr could never win.</p>
                        <p>Their superior technology was consistently outmanoeuvred by the Old Ones thanks to their mastery of the Webway portals and Warp Gates. The Necrontyr were pushed back until they were little more than an irritation to the Old Ones' dominance of the galaxy, a quiescent threat clinging to their irradiated world among the Halo Stars, exiled and forgotten.</p>
                        <p>The Necrontyr's fury was cooled by their long millennia of imprisonment on their homeworld, slowly transforming into an utter hatred towards all other forms of intelligent life and an implacable determination to avenge themselves upon their seemingly invincible enemies.</p>
                        <p>But in the face of defeat, the always fragile unity of the Necrontyr began to fracture once more. No longer did the prospect of a common enemy have any hold over the disparate dynasties.</p>
                        <p>Scores of generations had now lived and died in the service of an unwinnable war, and many Necrontyr dynasties would have gladly sued for peace with the Old Ones if the ruling Triarch had permitted it.</p>
                        <p>Thus began the second iteration of the Wars of Secession, more widespread and ruinous than any that had come before. So fractured had the Necrontyr dynasties become by then that, had the Old Ones been so inclined, they could have wiped out their foes with ease.</p>
                        <p>Faced with the total collapse of their rule, the Triarch searched desperately for a means of restoring order. In this, their prayers were answered, though the price for their species would be incalculably high.</p>
                        <p>It was during the reign of the Silent King Szarekh that the godlike energy beings known as the C'tan first blighted the Necrontyr. It is impossible to say for certain how the Necrontyr first made contact with the C'tan, though many misleading, contradictory and one-sided accounts of these events exist.</p>
                        <p>The dusty archives of the Tomb World of Solemnace claim it was but an accident, a chance discovery made by a stellar probe during the investigation of a dying star.</p>
                        <p>The Book of Mournful Night, held under close guard in the Aeldari Black Library's innermost sanctum, tells rather that the raw hatred that the Necrontyr held as a race for the Old Ones sang out across space, acting as a beacon that the C'tan could not ignore.</p>
                        <p>Another account claims that from the earliest days of their civilisation, Necrontyr scientists had been deeply engaged in stellar studies to try to understand and protect themselves from their own sun's baleful energies.</p>
                        <p>After long, bitter centuries of searching for some power to unleash upon the Old Ones, the Necrontyr researchers used stellar probes to discover unusual electrodynamic anomalies in the oldest, dying stars of the galaxy.</p>
                        <p>In the complex skeins of the energetic plasma of these suns, the Necrontyr found a sentience that was more ancient than that of any of the corporeal species in Creation, including the Old Ones.</p>
                        <p>They had discovered entities of pure energy that had spawned during the birth of the stars eons before. These entities had little conception of what the rest of the universe entailed when the Necrontyr first found them, instead simply feeding upon the solar flares and magnetic storms of these bloated red giants.</p>
                        <p>But here was the weapon the Necrontyr had long sought to bring about the downfall of the Old Ones, beings they believed the C'tan were the progeny of the death-god they worshipped. Howsoever first contact occurred, the shadow of the C'tan fell over the oldest Necrontyr dynasties first.</p>
                        <p>The power of these star-born creatures was incredible, the raw energy of the stars made animate, and the Necrontyr called them the C'tan or "Star Gods" in their own tongue. The C'tan were dispersed across areas larger than whole planets, their consciousnesses too vast for humanoids to comprehend. How the Necrontyr ever managed to communicate with them is unknown to the Adeptus Mechanicus.</p>
                        <p>Understanding that such diffuse minds could never perceive the material universe without manifesting themselves in a material form, some Necrontyr actively sought the C'tan's favour and oversaw the forging of physical shells for the C'tan to occupy, cast from the living metal called necrodermis.</p>
                        <p>Fragmentary Aeldari legends tell of translucent streamers of electromagnetic force shifting across space as the star vampires coiled into their new bodies in the physical realm across an incorporeal bridge of starlight. Thus clad, the C'tan took the physical shapes of the Necrontyr's half-forgotten ancient gods, hiding their own desires beneath cloaks of obsequious subservience.</p>
                        <p>Incomprehensible forces were compressed into the living metal of the necrodermis bodies which the Necrontyr had forged as the full power of the C'tan at last found form. As the C'tan focused their consciousnesses and became ever more aware of their new mode of existence, they came to appreciate the pleasures available to beings of matter and the other realities of corporeal life.</p>
                        <p>The deliciously focused trickles of electromagnetic energy given off by the physical bodies of the Necrontyr all about them awakened a new hunger in the C'tan very unlike the one they had once sated using the nourishing, but essentially tasteless, energies of the stars.</p>
                        <p>So it was that one of the C'tan came before the Silent King Szarekh, acting as forerunner to the coming of its brothers. Amongst its own kind, this C'tan was known as the "Deceiver," for it was willfully treacherous.</p>
                        <p>Yet the Silent King knew not the C'tan's true nature, and instead granted the creature an audience. The Deceiver spoke of a war, fought long before the birth of the Necrontyr, between the C'tan and the Old Ones. It was a war, he said, that the C'tan had lost.</p>
                        <p>In the aftermath, and fearing the vengeance of the Old Ones, the Deceiver and its brothers had hidden themselves away, hoping one day to find allies with whom they could finally bring the Old Ones to account. In return for this aid, the Deceiver assured, it and its brothers would deliver everything that the Necrontyr craved.</p>
                        <p>Unity could be theirs once again, and the immortality that they had sought for so long would finally be within their grasp. No price would their be for these great gifts, the Deceiver insisted, for they were but boons to be bestowed upon valued allies.</p>
                        <p>Thus did the Deceiver speak, and who can say how much of its tale was truth? It is doubtful whether even the Deceiver knew, for trickery had become so much a part of its existence that even the C'tan could no longer divine its root.</p>
                        <p>Yet the Deceiver's words held sway over Szarekh who, like his ancestors before him, despaired of the divisions that were tearing his people apart.</p>
                        <p>For long solar months he debated the matter with the other two phaerons of the Triarch and the nobles of his royal court. Through it all, the only dissenting voice was that of Orikan, the court astrologer, who foretold that the alliance between the Necrontyr and the C'tan would bring about a renaissance of glory, but destroy forever the soul of the Necrontyr people.</p>
                        <p>Yet desire and ambition swiftly overrode caution, and Orikan's prophecy was dismissed. A Necrontyr year after the Deceiver had presented his proposition, the Triarch agreed to the alliance, and so forever doomed their race.</p>
                        <p>For their part, the Necrontyr soon fell into awe of their discoveries and the C'tan moved to take control over their benefactors. The powers of the C'tan manifested in the physical world were indeed almost god-like and it was not long before the C'tan were being worshiped as the Star Gods the Necrontyr had named them.</p>
                        <p>Perhaps they had been tainted by the material universe they had become a part of, or perhaps this had always been their nature even when they were bound to the suns they fed upon, but the C'tan proved to be as cruel and capricious as the stars from which they had been born.</p>
                        <p>They soon revelled in the worship of the Necrontyr and feasted upon the life energies of countless mortal slaves.</p>
                        <p>Armed with weapons of god-like power and starships that could cross the galaxy in the blink of an eye, the Necrontyr stood ready to begin their war against the Old Ones anew. But the C'tan had another gift for their mortal subjects. They offered the Necrontyr a path to immortality and the physical stability their race had always craved.</p>
                        <p>Their diseased flesh would be replaced with the living metal of necrodermis that made up their Star Gods' own physical forms. The Necrontyr's discarded organic husks would be consumed and their cold, metal forms would then be free to pursue their great vengeance against the Old Ones and the rest of a hateful universe, freed forever from the weaknesses of their hated flesh.</p>
                        <p>With the pact between the Necrontyr and C'tan sealed, the Star Gods revealed the form that immortality would take for the Necrontyr, and the great biotransference process began.</p>
                        <p>Colossal cyclopean bio-furnaces built by Necrontyr artifice roared day and night, and into these the Silent King's peoples marched according to the terms of the pact he had made with the C'tan.</p>
                        <p>What blasphemous procedures the Necrontyr were subjected to within the raging bio-furnaces cannot be known, but certainly, each was stripped of flesh and of soul, their body replaced by a shell of living metal animated by what remained of their guttering self.</p>
                        <p>Above each furnace swooped and dove the ethereal true-forms of the C'tan as they glutted themselves on the cast off spiritual detritus and life energy of an entire species; growing ever stronger.</p>
                        <p>It was only when the Silent King himself emerged from the biotransference process and looked upon what had become of his people that he saw the awful truth of the pact he had made. As Szarekh watched the C'tan feast on the life essence of his people, he realised the terrible depth of his mistake.</p>
                        <p>In many ways, he felt better than he had in solar decades, the countless aches and uncertainties of organic life now behind him. His new machine body was far mightier than the frail form he had tolerated for so long, and his thoughts were swifter and clearer than they had ever been.</p>
                        <p>Yet there was an emptiness gnawing at his mind, an inexpressible hollowness of spirit that defied rational explanation. In that moment, he knew with cold certainty that the price of physical immortality had been the loss of his soul.</p>
                        <p>With great sorrow the Silent King beheld the fate he had brought upon his people: the Necrontyr were not but a memory, and the soulless, undying Necrons had been reborn in their place.</p>
                        <p>Yet though the price had been steep, biotransference had fulfilled all of the promises that the C'tan had made. Even the lowliest of the Necrontyr was now blessed with immortality -- age and hard radiation could little erode their new mechanical bodies, and only the most terrible of injuries could destroy them utterly.</p>
                        <p>Likewise, the Necrons now enjoyed a political unity that the Necrontyr had never known, though it was achieved through tyranny and the complete loss of individuality and emotion rather than by any form of consent.</p>
                        <p>The biotransference process had embedded command protocols in every machine-like Necron mind, granting Szarekh the unswerving if programmed loyalty of his subjects. At first, the Silent King embraced this species-wide unanimity, for it was a welcome reprieve from the chaos that had consumed the Necrontyr Empire in recent years.</p>
                        <p>However, as time wore on he grew weary of his burden, but dared not sever the command protocols lest his subjects turn on him seeking vengeance for the terrible curse he had visited upon them.</p>
                        <p>Thus the Necrontyr became the Necrons, cursed to the eternal servitude of their Star Gods. The C'tan feasted upon the entire Necrontyr race's life energies even as they made the transfers, leaving behind only the ghostly echoes of the Necrontyr's consciousnesses.</p>
                        <p>Only a few of the most strong-willed Necrontyr retained their intellect, personality and self-awareness, and even they were but shadows of their former selves. They had been purged of so much of what had made them unique individuals.</p>
                        <p>Yet most of the Necrons cared not at all for their loss; all that mattered to them was that they would live forever without disease or death as their Star Gods had promised.</p>
                        <p>The Necrontyr species was united as never before. The biotranserence process imbued in every one of the Silent King's subjects the command protocols with which he would rule over them with an iron hand. The entire species was now his to command as one, and so it fell upon the Necrons to honour their side of their terrible bargain.</p>
                        <p>Renewed by their devouring of the life energies of an entire species, the C'tan were now unstoppable, and with the legions of the Necrons marching in their wake, the Old Ones were doomed. Only one thing truly remained of the old Necrontyr -- their burning hatred for all the other living, intelligent species of the universe.</p>
                        <p>Legions of the undying living metal warriors set out into the galaxy in their Tomb Ships and the stars burned in their wake. The Old Ones' mastery of the Warp was now countered by the C'tan's supremacy over the physical universe, and the ancient enemies of the Necrons suffered greatly in the interstellar slaughter that followed.</p>

                    </section>

                </main>
            </div>
            <Footer />
        </>
    )
}

export default Necrons