import React from 'react'
import NavBar from '../NavBar/NavBar'
import Footer from '../Footer/Footer'
import './Eldars.css'
import eldarImg from '../../assets/EldarImg.jpg'
import eldarIco from '../../assets/eldarsIco.png'

function Eldars() {
    return (
        <>
            <NavBar />
            <div id='eldarsContainer'>
                <main className='eldarsMainsSection'>
                    <section className='eldarInfoSection'>
                        <h1> <img src={eldarIco} className='eldardsLogo' alt="" />Eldars <img src={eldarIco} className='eldardsLogo' alt="" /></h1>
                        <p>The Aeldari, or the Eldar as they were long known to outsiders, are an ancient and highly advanced species of humanoid xenos whose vast empire once extended the width and breadth of the known galaxy.</p>
                        <p>In its time, the Aeldari Empire was without equal in the galaxy, spreading across both realspace and the Webway. They counted themselves masters of the stars and every Aeldari was born a potent psyker, their abilities often used to both create and power their almost magical technology.</p>
                        <p>Even death was no barrier, for when the Aeldari's spirits eventually left their mortal bodies they dissolved peacefully back into the Immaterium to be reborn again in new forms, for the Warp did not thirst for Aeldari souls then as it does today.</p>

                        <p>But ten millennia ago, the Aeldari's overweening pride and their fall into amoral and hedonistic practices led to a cataclysm that all but eradicated their kind and resulted in the birth of the Chaos God Slaanesh, known as "She Who Thirsts" to the Aeldari.</p>
                        <p>Despite their boundless power, the heart of their civilisation was torn out by this catastrophe of their own making, forcing many of the surviving Aeldari to pursue different strategies for survival to protect their souls from being consumed by She Who Thirsts. These strategies have shaped the nature of the surviving Aeldari cultures.</p>
                        <p>In the 41st Millennium there are five major sub-cultures or kindreds of the Aeldari species: the Asuryani or Craftworld Aeldari, the Drukhari, the Harlequins, the Exodites, and the Ynnari.</p>
                        <p>There are also bands of independent Aeldari who survive by raiding other species' shipping and commerce, many of whom are Asuryani who have left the often rigid and confining culture of their people behind. They are known as the Asuryani Outcasts and the Aeldari Corsairs.</p>
                        <p>The Asuryani fled the original homeworlds of the Aeldari Empire in great, continent-sized starships called craftworlds. These craftworlds are now scattered across the galaxy, only connected to each other by the labyrinthine corridors of the Webway. The Asuryani seek to protect themselves from the hunger of She Who Thirsts through the use of a soul-capturing psychocrystalline technology known as Spirit Stones and a rigid code of behaviour called the Asuryani Path.</p>
                        <p>The Drukhari are the descendants of those Aeldari who originally settled within the Webway, particularly the ancient city of Commorragh. The Drukhari protect themselves from the hunger of Slaanesh by following what the Asuryani call the "Path of Damnation"; these piratical people revel in the physical and emotional pain of others, for feeding upon the psychic residue of suffering is the only way they can stave off the slow consumption by She Who Thirsts of their own souls.</p>
                        <p>The Harlequins are the servants of the Aeldari Laughing God Cegorach who fled into the Webway at the time of the Fall of the Aeldari and were protected from the thirst of Slaanesh by their god's power.</p>
                        <p>The Harlequins are the keepers of the Aeldari repository of Chaos knowledge known as the Black Library and they are the only Aeldari who still move freely among all of the other factions. Their purpose is to maintain among their fellows the knowledge of the Aeldari mythological cycles that form the foundation of all Aeldari culture.</p>
                        <p>The Exodites are those Aeldari who fled the ancient homeworlds before the Fall and chose to settle on verdant, unsettled planets known as Maiden Worlds. The Exodites are protected from the soul-thirst of Slaanesh by unifying their souls upon death with the World Spirits of their home planets and from the darker impulses of the Aeldari psyche by pursuing lifestyles marked by more hardship and less labour-saving technology than any of their brethren.</p>
                        <p>The Ynnari, also called the Reborn, are a religious sect of Aeldari drawn from all of the other factions who serve the partially awakened Aeldari god of the dead Ynnead. Led by Ynnead's high priestess and chosen prophet, Yvraine, the Daughter of Shades, the Ynnari came into existence just before the birth of the Great Rift and the start of the Era Indomitus.</p>
                        <p>The Reborn seek nothing less than the full awakening of Ynnead, who will then do battle with Slaanesh, destroy the Chaos God and restore the Aeldari people to their lost greatness. Ynnari no longer need fear Slaanesh's thirst, for upon death they become one with Ynnead.</p>
                    </section>
                    <section className='eldarHistorySection'>
                        <h1>History</h1>
                        <p>The ancient history of the Aeldari stretches back over the millennia to a time when they dominated the stars completely. Yet, for all their splendour and might, the Aeldari brought a terrible curse upon themselves that sundered their empire forever, leaving the ravaged fragments of their race teetering on the brink of annihilation.</p>
                        <p>The ancient history of the Aeldari stretches back over the millennia to a time when they dominated the stars completely. Yet, for all their splendour and might, the Aeldari brought a terrible curse upon themselves that sundered their empire forever, leaving the ravaged fragments of their race teetering on the brink of annihilation.</p>
                        <p>The starfaring history of the Aeldari is long, and encompasses glories and sorrows alike. When the Aeldari Empire was at its height, their homeworlds were paradises, their powers godlike and their armies unsurpassed. As the Terran centuries slid past, their status as lords of the galaxy bred an arrogance that led to a cataclysm.</p>
                        <p>A proportion of their race survived that dark time by fleeing from disaster upon the great vessels known as craftworlds. Others settled verdant planets far from the heart of their empire, and still more hid in private realms of their own making. Yet there was no real escape from what was to come.</p>
                        <p>Apparent perfection like that of the ancient Aeldari is all too often blighted by pride. Over a million Terran years ago, the Aeldari alone ruled the stars as the undisputed masters of their own destiny. Such a position was their right, they thought, and their preeminence was beyond doubt.</p>
                        <p>In many ways, the Aeldari had good reason for such hubris, for no other race had posed a serious threat to their wealth and stability for time immemorial. They were convinced that they no longer had anything to fear from the galaxy at large, and they may have been right, but the true threat came from within. The doom of the Aeldari, when it came, took a form far more subtle and dangerous than that of alien invasion.</p>
                        <p>At their peak, nothing was beyond the Aeldari's reach and nothing was forbidden. The ancient race continued their glorious existence unaware or unwilling to acknowledge the dark fate that awaited them. They plied the stars at will, experiencing the wonders of the galaxy and immersing themselves completely in the endless sensations that it offered them. Such was the technological mastery of the Aeldari that worlds were created specifically for their pleasure, and stars lived or died at their whim.</p>
                        <p>On hundreds of idyllic planets seeded across the stars, the Aeldari pursued their inclinations as they willed, indulging every dream and investigating every curiosity. They mastered the labyrinth dimension of the Webway, expanded their realms into the furthest corners of reality and learned much about the universe that has since been forgotten.</p>
                        <p>When their spirits eventually left their mortal bodies at death, they dissolved peacefully back into the Empyrean to be reborn again, for the Warp did not yet hold the danger for Aeldari souls that it has since their Fall.</p>
                        <p>There were, of course, many wars. Even when the galaxy was young there were upstart species seeking to gouge out petty empires of their own, and the Aeldari waged wars against the sprawling Necron dynasties that ravaged dozens of star systems and cost trillions of lives. Most of these conflicts, though, were so short-lived that the ease of their victory left the Aeldari ever more sure of their ascendancy.</p>
                        <p>Even the greatest of all their wars, the conflict over sixty million Terran years ago that first forged their species in alliance with the legendary beings called the Old Ones, dimly remembered in the mythic cycles of the craftworlds as the War in Heaven, did not humble them. In their hearts the Aeldari reigned supreme, and no other power could end their dominance.</p>
                        <br />
                        <h3>Descent into Darkness</h3>
                        <p>The catalyst that brought about the Aeldari race's fall came from the very depths of their collective psyche, the innate need to fuel their passions and indulge in every extreme. Their people had long outgrown the need for physical labour or manual agriculture due to the highly advanced and automated nature of their technology.</p>
                        <p>Aeldari society provided all the required necessities of life without individual effort, leaving long Terran centuries for the Aeldari to spend sating their every desire and whim.</p>
                        <p>Fuelled by an inexhaustible curiosity, many gave way to their most hedonistic impulses. Exotic cults sprang up across the Aeldari domains that eclipsed the noble pursuits of old, each dedicated to esoteric knowledge or sensual excess.</p>
                        <p>The core of the Aeldari race began to look inwards, inexorably seeking new ways to explore the full range of emotion and sensation. Such behaviour was perilously decadent and, in the end, corrosive to the soul of the race. The pursuit of excess gradually became a blight upon the whole society.</p>
                        <p>The acts of the pleasure cults began to transcend those of idle curiosity, or even extreme addiction. Aeldari from every corner of the empire wallowed in their most unnatural impulses in the pursuit of debauchery. As the cults gained a tighter hold over their society, the Aeldari became increasingly divided.</p>
                        <p>Those who saw the foulness that corrupted their people for what it was became known as Exodites, and they departed to found colony worlds on the fringes of the Aeldari Empire. As the civilisation slid further into anarchy, others repented of their ways and fled into deep space aboard world-ships called craftworlds. Most Aeldari, however, continued to glut themselves on the pursuits of the depraved.</p>
                        <p>The sorrow of those left who mourned the loss of innocence eventually turned to bitterness and spite. In time, brother fought brother, and sadistic killers stalked the shadows in search of victims for their vile lusts. No life was spared in the pursuit of pleasures both murderous and perverse. A sickness of vice overtook the Aeldari race, and blood flowed through the streets amidst the bestial roar of the crowd.</p>
                        <p>Their hidden realms within the Webway -- the network of tunnels that spread between realspace and the Warp – became sprawling palaces of avarice and sadism, and entire worlds were bent to the pursuit of the darkest of sensations.</p>
                        <p>As the moral corruption of the Aeldari race tightened its stranglehold, echoes of ecstasy and agony began to ripple through time and space. In the parallel dimension of the Immaterium, the psychic reflections of these intense experiences began to coalesce, for the shifting tides of the Empyrean can take form around intense emotion. Slowly, silently, a nascent god of excess grew strong in the depths of the Warp.</p>
                        <br />
                        <h3>Birth of a Dark God</h3>
                        <p>Within the Warp, thoughts and emotions generated in realspace flow together in the form of psychic energy, fed by fellow feelings until they achieve a consciousness of sorts. They become entities of greater or lesser potency depending on the intensity of their origin. Amidst the swirling psychic energy of the Empyrean, the corruption of the decadent Aeldari became manifest on a horrifying scale as the flood of raw emotions coalesced into a gestalt consciousness.</p>
                        <p>What an unimaginably foul and sickening thing it was that the Aeldari unknowingly raised in the Warp; it was a dire shadow of themselves, of what they had become, of nobility and pride brought low by perversity and shamelessness.</p>
                        <p>Worlds burned as the Aeldari slew and laughed and feasted upon the corpses of the dead. Slowly, the Great Enemy stirred towards wakefulness. Too late, the Aeldari realised that they had created a god in their own hideous image, a god grown immense and potent by suckling upon the dark fodder of the Aeldari soul.</p>
                        <p>No creature was ever conceived that was as terrible or perverse as the major Chaos God Slaanesh. It is a name the Aeldari will not speak, instead whispering Sai'lanthresh, translatable into Low Gothic as "She Who Thirsts."</p>
                        <p>When Slaanesh finally burst into divine consciousness, there was not one Aeldari alive who did not feel its claws in their soul. With a howl of raw power, Slaanesh roared into supernatural life. A psychic implosion tore at the universe. Countless billions of Aeldari screamed aloud and fell dead.</p>
                        <p>From the moment that Slaanesh burst into being, the soul of every living Aeldari was forfeit. Upon the death of the body, an unprotected Aeldari soul would be dragged into the Warp, and thence to an eternity of hideous torment within the psychic gullet of She Who Thirsts.</p>
                        <p>In a heartbeat, the shining Aeldari civilisation that had lasted for aeons had its heart ripped out, leaving a pulsing afterbirth of pure chaos in its place. The spirits of the Aeldari were drawn from within them and consumed as their blasphemous creation took its first infernal breath. Intoxicated with this potent draught of billions of souls, Slaanesh laughed and looked upon a universe ripe for the taking.</p>
                    </section>
                </main>
            </div>
            <Footer />
        </>
    )
}

export default Eldars